
server:
  port: ${PORT:8081}
#  servlet:
#    context-path: /swarmhr-gateway
#management:
#  security:
#    enabled: false
spring:
  #profile: uat
  application:
    name: masterhr-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/prasad
    username: root
    password: root
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl: none
        format_sql: true
        show_sql: true
#
#logging:
#  file: /apps/opt/application/runnable/Swarmhr-Nextgen/SwarmHRGateway/logs/SwarmHRGateway.log
#  level:
#    org.springframework.web: INFO
#    com.swarmhr.user: DEBUG
#    org.hibernate: ERROR
#
#google:
#  cloud: 
#    datastore: 
#      config-file-name: E:/Prasad Softwares/AtsConfig/AtsConfig/testswarmhr-uat-datastore.json 
#    storage:
#      config-file-name: E:/Prasad Softwares/AtsConfig/AtsConfig/testswarmhr-uat.json
#    projectId: twssemployeeportal
#
#swarmhr:
#  site-url: https://uat-env.swarmhr.com

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761}
    registerWithEureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 300

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignored-headers:
   Access-Control-Allow-Credentials
   Access-Control-Allow-Origin
  prefix: /api
  routes:
#    swarmhr-admin:
#      path: /swarmhr-admin/**
#      service-id: swarmhr-admin-service
#      url: http://localhost:9090/swarmhr-admin
    masterhr-user:
      path: /masterhr-user/**
      service-id: masterhr-user-service
#     url: http://localhost:8899/swarmhr-user
#    swarmhr-manager:
#      path: /swarmhr-manager/**
#      service-id: swarmhr-manager-service
#    swarmhr-common:
#      path: /swarmhr-common/**
#      service-id: swarmhr-common-service
#    swarmhr-invoice:
#      path: /swarmhr-invoice/**
#      service-id: swarmhr-invoice-service
#    swarmhr-document:
#      path: /swarmhr-document/**
#      service-id: swarmhr-document-service
#    swarmhr-spadmin:
#      path: /swarmhr-spadmin/**
#      service-id: swarmhr-spadmin-service
#    swarmhr-reports:
#      path: /swarmhr-reports/**
#      service-id: swarmhr-reports-service
ribbon:
  eureka:
    enabled: false
    
masterhr-user-service:
  ribbon:
    listOfServers: localhost:8899
    ReadTimeout: 60000

   
   